processors:
  resource:
    attributes:
      - key: appdynamics.controller.account
        action: upsert
        value: "xxxx"
      - key: appdynamics.controller.host
        action: upsert
        value: "xxxx"
      - key: appdynamics.controller.port
        action: upsert
        value: 443
      - key: service.namespace
        action: upsert
        value: "xxxx"
      - key: service.name
        value: "xxxx"
        action: upsert
  batch:
    timeout: 30s
    send_batch_size: 90
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "https://xxxx.saas.appdynamics.com"
    headers: { "x-api-key": "xxxx" }
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlphttp, otlp, debug]
  telemetry:
    logs:
      level: "debug"
